// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// WatcherInterface is an autogenerated mock type for the WatcherInterface type
type WatcherInterface struct {
	mock.Mock
}

// Stop provides a mock function with given fields:
func (_m *WatcherInterface) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Watch provides a mock function with given fields:
func (_m *WatcherInterface) Watch() {
	_m.Called()
}
