// Code generated by MockGen. DO NOT EDIT.
// Source: pkg/ui/view.go
//
// Generated by this command:
//
//	mockgen -source=pkg/ui/view.go -destination=pkg/ui/view_mock.go -package=ui
//

// Package ui is a generated GoMock package.
package ui

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockView is a mock of View interface.
type MockView struct {
	ctrl     *gomock.Controller
	recorder *MockViewMockRecorder
}

// MockViewMockRecorder is the mock recorder for MockView.
type MockViewMockRecorder struct {
	mock *MockView
}

// NewMockView creates a new mock instance.
func NewMockView(ctrl *gomock.Controller) *MockView {
	mock := &MockView{ctrl: ctrl}
	mock.recorder = &MockViewMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockView) EXPECT() *MockViewMockRecorder {
	return m.recorder
}

// GetName mocks base method.
func (m *MockView) GetName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetName indicates an expected call of GetName.
func (mr *MockViewMockRecorder) GetName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetName", reflect.TypeOf((*MockView)(nil).GetName))
}

// Write mocks base method.
func (m *MockView) Write(str string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Write", str)
}

// Write indicates an expected call of Write.
func (mr *MockViewMockRecorder) Write(str any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockView)(nil).Write), str)
}

// Writef mocks base method.
func (m *MockView) Writef(str string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{str}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Writef", varargs...)
}

// Writef indicates an expected call of Writef.
func (mr *MockViewMockRecorder) Writef(str any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{str}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Writef", reflect.TypeOf((*MockView)(nil).Writef), varargs...)
}
