// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	config "github.com/eko/monday/pkg/config"
	mock "github.com/stretchr/testify/mock"
)

// Runner is an autogenerated mock type for the Runner type
type Runner struct {
	mock.Mock
}

// Restart provides a mock function with given fields: application
func (_m *Runner) Restart(application *config.Application) {
	_m.Called(application)
}

// Run provides a mock function with given fields: application
func (_m *Runner) Run(application *config.Application) {
	_m.Called(application)
}

// RunAll provides a mock function with given fields:
func (_m *Runner) RunAll() {
	_m.Called()
}

// SetupAll provides a mock function with given fields:
func (_m *Runner) SetupAll() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *Runner) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
