// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import config "github.com/eko/monday/pkg/config"
import mock "github.com/stretchr/testify/mock"

// RunnerInterface is an autogenerated mock type for the RunnerInterface type
type RunnerInterface struct {
	mock.Mock
}

// Restart provides a mock function with given fields: application
func (_m *RunnerInterface) Restart(application *config.Application) {
	_m.Called(application)
}

// Run provides a mock function with given fields: application
func (_m *RunnerInterface) Run(application *config.Application) {
	_m.Called(application)
}

// RunAll provides a mock function with given fields:
func (_m *RunnerInterface) RunAll() {
	_m.Called()
}

// SetupAll provides a mock function with given fields:
func (_m *RunnerInterface) SetupAll() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *RunnerInterface) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
