// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	proxy "github.com/eko/monday/pkg/proxy"
	mock "github.com/stretchr/testify/mock"
)

// Proxy is an autogenerated mock type for the Proxy type
type Proxy struct {
	mock.Mock
}

// AddProxyForward provides a mock function with given fields: name, proxyForward
func (_m *Proxy) AddProxyForward(name string, proxyForward *proxy.ProxyForward) {
	_m.Called(name, proxyForward)
}

// Listen provides a mock function with given fields:
func (_m *Proxy) Listen() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *Proxy) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
