// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"
import proxy "github.com/eko/monday/pkg/proxy"

// ProxyInterface is an autogenerated mock type for the ProxyInterface type
type ProxyInterface struct {
	mock.Mock
}

// AddProxyForward provides a mock function with given fields: name, proxyForward
func (_m *ProxyInterface) AddProxyForward(name string, proxyForward *proxy.ProxyForward) {
	_m.Called(name, proxyForward)
}

// Listen provides a mock function with given fields:
func (_m *ProxyInterface) Listen() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *ProxyInterface) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
