// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// HostfileInterface is an autogenerated mock type for the HostfileInterface type
type HostfileInterface struct {
	mock.Mock
}

// AddHost provides a mock function with given fields: ip, hostname
func (_m *HostfileInterface) AddHost(ip string, hostname string) error {
	ret := _m.Called(ip, hostname)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(ip, hostname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RemoveHost provides a mock function with given fields: hostname
func (_m *HostfileInterface) RemoveHost(hostname string) error {
	ret := _m.Called(hostname)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(hostname)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
