// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Forwarder is an autogenerated mock type for the Forwarder type
type Forwarder struct {
	mock.Mock
}

// ForwardAll provides a mock function with given fields:
func (_m *Forwarder) ForwardAll() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *Forwarder) Stop() {
	_m.Called()
}
