// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ForwarderInterface is an autogenerated mock type for the ForwarderInterface type
type ForwarderInterface struct {
	mock.Mock
}

// ForwardAll provides a mock function with given fields:
func (_m *ForwarderInterface) ForwardAll() {
	_m.Called()
}

// Stop provides a mock function with given fields:
func (_m *ForwarderInterface) Stop() {
	_m.Called()
}
