// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ViewInterface is an autogenerated mock type for the ViewInterface type
type ViewInterface struct {
	mock.Mock
}

// GetName provides a mock function with given fields:
func (_m *ViewInterface) GetName() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Write provides a mock function with given fields: str
func (_m *ViewInterface) Write(str string) {
	_m.Called(str)
}

// Writef provides a mock function with given fields: str, args
func (_m *ViewInterface) Writef(str string, args ...interface{}) {
	var _ca []interface{}
	_ca = append(_ca, str)
	_ca = append(_ca, args...)
	_m.Called(_ca...)
}
